apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: event-booking
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
        - name: event-service
          image: event-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres:5432/event_db
            - name: REDIS_URL
              value: redis://redis:6379
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: event-booking
spec:
  type: NodePort
  selector:
    app: event-service
  ports:
    - port: 3002
      targetPort: 3002
      nodePort: 30002
